### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by ugintl** [midnite81/plivo#9]
I want to install plivo on php, mysql, apache hosting

Is it possible?

**Comment by midnite81** [comment]
This is a PHP package which wraps commands to interact with the Plivo API. Depending on what you mean by installing Plivo will very much depend on the answer. 

If you mean can you install this package on your server then the answer is yes, if you're asking if you can install the Plivo SMS server on your server then the answer is no.

Since the time of writing this API wrapper they have bought out a newer version of the API so you might be best off using [https://github.com/plivo/plivo-php](https://github.com/plivo/plivo-php).

It seems as though you are relatively new to web development, so you might want to learn about composer ([https://getcomposer.org/doc/00-intro.md](https://getcomposer.org/doc/00-intro.md)) before you try and install this.
